// Module2_FrontendDev/Jagadeeswari_D/handson_8/student-portal-vue/src/components/CourseCard.vue
<template>
  <div class="course-card">
    <h2>{{ name }}</h2>
    <p><strong>Code:</strong> {{ code }}</p>
    <p><strong>Credits:</strong> {{ credits }}</p>
    <p><strong>Grade:</strong> {{ grade }}</p>
  </div>
</template>

<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String
});
</script>

<style scoped>
.course-card {
  border: 1px solid #ccc;
  padding: 15px;
  margin: 10px;
  border-radius: 8px;
}
</style>

// Module2_FrontendDev/Jagadeeswari_D/handson_5/src/components/CourseCard.jsx
function CourseCard(props) {
  return (
    <div className="course-card">
      <h2>{props.name}</h2>
      <p>Code: {props.code}</p>
      <p>Credits: {props.credits}</p>
      <p>Grade: {props.grade}</p>

      <button onClick={() => props.onEnroll(props)}>
        Enroll
      </button>
    </div>
  );
}

export default CourseCard;
