// Module2_FrontendDev/Jagadeeswari_D/handson_7/student-portal-angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  standalone: true,
  imports: [],
  templateUrl: './course-card.html',
  styleUrl: './course-card.css'
})
export class CourseCard {

  @Input() name = '';
  @Input() code = '';
  @Input() credits = 0;
  @Input() grade = '';

}

// Module2_FrontendDev/Jagadeeswari_D/handson_5/src/components/CourseCard.jsx
function CourseCard(props) {
  return (
    <div className="course-card">
      <h2>{props.name}</h2>
      <p>Code: {props.code}</p>
      <p>Credits: {props.credits}</p>
      <p>Grade: {props.grade}</p>

      <button onClick={() => props.onEnroll(props)}>
        Enroll
      </button>
    </div>
  );
}

export default CourseCard;
