// Module2_FrontendDev/Jagadeeswari_D/handson_8/student-portal-vue/src/components/Header.vue
<template>
  <header>

    <h1>
      Student Portal ({{ store.enrolledCourses.length }})
    </h1>

    <nav>
      <RouterLink to="/">Home</RouterLink>

      |

      <RouterLink to="/courses">Courses</RouterLink>

      |

      <RouterLink to="/profile">Profile</RouterLink>
    </nav>

    <hr />

  </header>
</template>

<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<style scoped>
nav {
  display: flex;
  gap: 15px;
  margin: 15px 0;
}
</style>

// Module2_FrontendDev/Jagadeeswari_D/handson_6/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header() {
  const enrolledCourses = useSelector(
    (state) => state.enrollment.enrolledCourses
  );

  return (
    <header>
      <h1>Student Portal</h1>

      <nav>
        <Link to="/">Home</Link>{" | "}
        <Link to="/courses">Courses</Link>{" | "}
        <Link to="/profile">Profile</Link>
      </nav>

      <p>Enrolled Courses: {enrolledCourses.length}</p>

      <hr />
    </header>
  );
}

export default Header;
